import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "BEACON EXPO",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/images/logo-beacon.png", type: "image/png" }],
    apple: [{ url: "/images/logo-beacon.png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
